version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: brenda2802
      POSTGRES_DB: picpay-desafio
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: picpay-desafio
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/picpay-desafio
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: brenda2802
    ports:
      - "8080:8080"